echo "LINEAR_API_KEY=${LINEAR_API_KEY}" >> .env
echo "CYCLE_START_DATE=${CYCLE_START_DATE}" >> .env
echo "CYCLE_END_DATE=${CYCLE_END_DATE}" >> .env
echo "GITHUB_EVENT_NAME"=${GITHUB_EVENT_NAME} >> .env
echo "POST_TO_SLACK=${POST_TO_SLACK}" >> .env
echo "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}" >> .env
echo "SLACK_WEBHOOK_TRR_QA_BOT=${SLACK_WEBHOOK_TRR_QA_BOT}" >> .env
