name: CFD Stats Bi-Weekly

on:
  workflow_dispatch:
    inputs:
      cycleStart:
        description: 'cycle start date : format 2024-12-16'
        required: false
        default: ''
        type: string
      cycleEnd:
        description: 'cycle end date : format 2024-12-29'
        required: false
        default: ''
        type: string
  schedule:
    - cron: '30 4 * * 1' # Runs every Monday at 10 AM IST

jobs:
  run-main-ts:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: |
          npm install
          npm install -g ts-node typescript

      - name: Create Environment File
        run: sh scripts/create-env.sh
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          CYCLE_START: ${{ github.event.inputs.cycleStart }}
          CYCLE_END: ${{ github.event.inputs.cycleEnd }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TRR_QA_BOT: ${{ secrets.SLACK_WEBHOOK_TRR_QA_BOT }}

      - name: Run main.ts
        id: test
        run: npm run start

      - name: Save Logs
        if: always() && steps.test.outcome == 'success' || steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        id: logs-upload-step
        with:
          name: logs-${{ github.run_id }}
          path: logs/
